name: Unified-Reusable-Workflow CI/CD

on:
  workflow_call:
    inputs:
      terraform-dir:
        description: 'Directory containing Terraform configuration'
        required: false
        default: './terraform'
        type: string
      python-dir:
        description: 'Directory for Python app/code'
        required: false
        default: './app'
        type: string
      shell-script:
        description: 'Path to shell script to execute'
        required: false
        default: './terraform/shell-scripts/validate.sh'
        type: string
    secrets:
        AWS_ACCESS_KEY_ID:
            description: 'AWS Access Key ID'
            required: true
        AWS_SECRET_ACCESS_KEY:
            description: 'AWS Secret Access Key'
            required: true
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Format Check
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -input=false
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -input=false

  python:
    name: Python Lint and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.python-dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
      - name : Check code formatting
        run: |
          . .venv/bin/activate
          black --check . || true  # (Add black to requirements.txt)
      - name: Lint Python code
        run: |
          . .venv/bin/activate
          flake8 . || true  # (Add flake8 to requirements.txt)
      - name: Run unit tests
        run: |
          . .venv/bin/activate
          pytest

  shell:
    name: Shell Script Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run custom shell script
        run: bash ${{ inputs.shell-script }}

  # Add additional jobs (e.g., nodejs, yaml-lint, docker build) as needed.